# Taps
tap "cameroncooke/axe"
tap "felixkratz/formulae"
tap "jesseduffield/lazydocker"
tap "nikitabobko/tap"
tap "supabase/tap"

# CLI tools
brew "actionlint"
brew "atac"
brew "cameroncooke/axe/axe"
brew "bat"                   
brew "btop"                  
brew "cmake"
brew "cmatrix"
brew "cocoapods"
brew "docker"
brew "docker-compose"
brew "eza"
brew "fastlane"
brew "fd"
brew "fnm"
brew "fzf"                    
brew "gh"                     
brew "git"
brew "git-delta"
brew "git-filter-repo"
brew "git-gui"
brew "git-lfs"
brew "glow"                   
brew "go"
brew "httpd"
brew "jq"                     
brew "jesseduffield/lazydocker/lazydocker" 
brew "ninja"
brew "pipx"
brew "prettyping"
brew "pyenv"                  
brew "rbenv"
brew "uv"                     # Fast Python package installer                  
brew "ripgrep"
brew "felixkratz/formulae/sketchybar"
brew "sl"
brew "sshs"
brew "stow"                   
brew "supabase/tap/supabase"
brew "terminal-notifier"
brew "tmux"
brew "trash-cli", link: true 
brew "tree"
brew "watchman"
brew "webp" 
brew "yarn"
brew "zippoxer/tap/recall"
brew "zoxide"                 
brew "zsh-autocomplete"
brew "zsh-autosuggestions"
brew "zsh-vi-mode"

# GUI Applications (casks)
cask "nikitabobko/tap/aerospace"
cask "android-platform-tools"
cask "arc"
cask "chromium"
cask "cursor"
cask "orbstack"
cask "figma"
cask "font-hack-nerd-font"
cask "font-sf-pro"
cask "font-sketchybar-app-font"
cask "ghostty"
cask "kindavim"
cask "ngrok"
cask "raycast"
cask "sf-symbols"
cask "spotify"
cask "superwhisper"
cask "visual-studio-code"

# VS Code / Cursor extensions
# Note: These are installed to Cursor via setup/cursor-extensions.sh
# The vscode entries here are kept for reference and will install to VSCode if present
# To install only to Cursor, you can remove visual-studio-code cask above
vscode "anthropic.claude-code"
vscode "ms-pyright.pyright"
vscode "bradlc.vscode-tailwindcss"
vscode "catppuccin.catppuccin-vsc"
vscode "christian-kohler.path-intellisense"
vscode "dbaeumer.vscode-eslint"
vscode "ecmel.vscode-html-css"
vscode "esbenp.prettier-vscode"
vscode "expo.vscode-expo-tools"
vscode "firsttris.vscode-jest-runner"
vscode "formulahendry.code-runner"
vscode "github.vscode-github-actions"
vscode "github.vscode-pull-request-github"
vscode "kevinrose.vsc-python-indent"
vscode "lokalise.i18n-ally"
vscode "mikestead.dotenv"
vscode "ms-azuretools.vscode-docker"
vscode "ms-python.debugpy"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-wsl"
vscode "ms-vscode.makefile-tools"
vscode "msjsdiag.vscode-react-native"
vscode "naumovs.color-highlight"
vscode "pkief.material-icon-theme"
vscode "redhat.vscode-yaml"
vscode "ritwickdey.liveserver"
vscode "dsznajder.es7-react-js-snippets"
vscode "shd101wyy.markdown-preview-enhanced"
vscode "sswg.swift-lang"
vscode "steoates.autoimport"
vscode "svelte.svelte-vscode"
vscode "tamasfe.even-better-toml"
vscode "unifiedjs.vscode-mdx"
vscode "vadimcn.vscode-lldb"
vscode "vscodevim.vim"
vscode "wakatime.vscode-wakatime"
vscode "yoavbls.pretty-ts-errors"
vscode "yzhang.markdown-all-in-one"
vscode "illixion.vscode-vibrancy-continued"
vscode "RimuruChan.vscode-fix-checksums-next"

